# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mintor_data', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('timestamp', models.CharField(max_length=255)),
            ],
        ),
    ]
